#cloud-config
# version: main (slim) -- bootstrap.sh fetches large scripts from GitHub
package_update: false
package_upgrade: false
bootcmd:
  - [bash, -lc, "mkdir -p /var/lib/init-status;[ -f /var/lib/init-status/setup-complete ]&&exit 0;echo 0>/var/lib/init-status/stage;echo 1>/var/lib/init-status/phase;echo \"$(date -u +%Y-%m-%dT%H:%M:%SZ) STAGE=0 PHASE=1 DESC=init\">>/var/log/init-stages.log;systemctl stop apt-daily.timer apt-daily-upgrade.timer apt-daily.service apt-daily-upgrade.service unattended-upgrades 2>/dev/null||true;systemctl disable apt-daily.timer apt-daily-upgrade.timer 2>/dev/null||true;killall -9 unattended-upgr apt apt-get dpkg 2>/dev/null||true"]
  - [bash, -lc, "[ -f /var/lib/init-status/phase2-complete ]&&exit 0;systemctl stop xrdp xrdp-sesman 2>/dev/null||true;systemctl mask xrdp xrdp-sesman 2>/dev/null||true"]
  - [bash, -lc, "[ -f /var/lib/init-status/setup-complete ]&&exit 0;mkdir -p /tmp/downloads;curl -sL https://nodejs.org/dist/v22.12.0/node-v22.12.0-linux-x64.tar.xz -o /tmp/downloads/node.tar.xz& echo $!>/tmp/downloads/node.pid;wget -q -O /tmp/downloads/chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb& echo $!>/tmp/downloads/chrome.pid"]
  - [bash, -lc, "[ -f /var/lib/init-status/setup-complete ]&&[ ! -f /var/lib/init-status/boot-complete ]&&{ echo 11>/var/lib/init-status/stage;echo \"$(date -u +%Y-%m-%dT%H:%M:%SZ) STAGE=11 DESC=ready\">>/var/log/init-stages.log;touch /var/lib/init-status/boot-complete;}||true"]
write_files:
  - path: /etc/hatchery-version
    content: "main"
  - path: /etc/droplet.env
    owner: root:root
    permissions: "0600"
    content: |
      USERNAME="bot"
      SSH_KEY_B64=""
      DO_TOKEN_B64="[[DO_TOKEN_B64]]"
      PASSWORD_B64="[[PASSWORD_B64]]"
      # PLATFORM, DISCORD_*, TELEGRAM_OWNER_ID are extracted from HABITAT_B64
      # by parse-habitat.py -> /etc/habitat-parsed.env (no Shortcut placeholders needed)
      ANTHROPIC_KEY_B64="[[ANTHROPIC_KEY_B64]]"
      BRAVE_KEY_B64="[[BRAVE_KEY_B64]]"
      GOOGLE_API_KEY_B64="[[GOOGLE_API_KEY_B64]]"
      DROPBOX_TOKEN_B64="[[DROPBOX_TOKEN_B64]]"
      EMAIL_B64="[[EMAIL_B64]]"
      IMAP_HOST_B64="[[IMAP_HOST_B64]]"
      SMTP_HOST_B64="[[SMTP_HOST_B64]]"
      EMAIL_PASSWORD_B64="[[EMAIL_PASSWORD_B64]]"
      CALDAV_URL_B64="[[CALDAV_URL_B64]]"
      CALDAV_USER_B64="[[CALDAV_USER_B64]]"
      CALDAV_PASSWORD_B64="[[CALDAV_PASSWORD_B64]]"
      API_SECRET_B64="[[API_SECRET_B64]]"
      GH_TOKEN_B64="[[GH_TOKEN_B64]]"
      GMAIL_CLIENT_ID_B64="[[GMAIL_CLIENT_ID_B64]]"
      GMAIL_CLIENT_SECRET_B64="[[GMAIL_CLIENT_SECRET_B64]]"
      GMAIL_REFRESH_TOKEN_B64="[[GMAIL_REFRESH_TOKEN_B64]]"
      OPENAI_ACCESS_B64="[[OPENAI_ACCESS_B64]]"
      OPENAI_REFRESH_B64="[[OPENAI_REFRESH_B64]]"
      OPENAI_EXPIRES_B64="[[OPENAI_EXPIRES_B64]]"
      OPENAI_ACCOUNT_ID_B64="[[OPENAI_ACCOUNT_ID_B64]]"
      HABITAT_B64="[[HABITAT_B64]]"
      AGENT_LIB_B64="[[AGENT_LIB_B64]]"
  - path: /etc/needrestart/conf.d/99-autorestart.conf
    permissions: "0644"
    content: |
      $nrconf{restart} = 'a';
      $nrconf{blacklist_rc} = [qr/^cloud-init/, qr/^cloud-final/, qr/^cloud-config/];
  - path: /etc/ssh/sshd_config.d/99-password-auth.conf
    permissions: "0644"
    content: |
      PasswordAuthentication yes
      PermitRootLogin yes
  - path: /usr/local/bin/set-stage.sh
    permissions: "0755"
    content: |
      #!/bin/bash
      echo "$1">/var/lib/init-status/stage
      echo "$(date -u +%Y-%m-%dT%H:%M:%S.%3NZ) STAGE=$1 PHASE=$(cat /var/lib/init-status/phase 2>/dev/null||echo 1) DESC=$2">>/var/log/init-stages.log
  - path: /usr/local/bin/set-phase.sh
    permissions: "0755"
    content: |
      #!/bin/bash
      echo "$1">/var/lib/init-status/phase
      echo "$(date -u +%Y-%m-%dT%H:%M:%S.%3NZ) PHASE=$1 DESC=$2">>/var/log/init-stages.log
  - path: /usr/local/bin/set-council-group.sh
    permissions: "0755"
    content: |
      #!/bin/bash
      set -a;source /etc/droplet.env;set +a
      d(){ [ -n "$1" ]&&echo "$1"|base64 -d 2>/dev/null||echo "";}
      P="${PLATFORM:-$(d "$PLATFORM_B64")}";[ "${P:-telegram}" = "discord" ]&&exit 0
      exec /usr/local/bin/set-council-group.telegram.sh "$@"
  - path: /etc/systemd/system/post-boot-check.service
    permissions: "0644"
    content: |
      [Unit]
      Description=Post-boot health check
      After=clawdbot.service network-online.target
      Wants=network-online.target
      [Service]
      Type=oneshot
      ExecStart=/usr/local/bin/post-boot-check.sh
      RemainAfterExit=yes
      [Install]
      WantedBy=multi-user.target
  - path: /etc/systemd/system/clawdbot-sync.service
    permissions: "0644"
    content: |
      [Unit]
      Description=Sync Clawdbot memory to Dropbox
      [Service]
      Type=oneshot
      ExecStart=/usr/local/bin/sync-openclaw-state.sh
      User=root
  - path: /etc/systemd/system/clawdbot-sync.timer
    permissions: "0644"
    content: |
      [Unit]
      Description=Periodic Clawdbot memory sync
      [Timer]
      OnBootSec=2min
      OnUnitActiveSec=2min
      [Install]
      WantedBy=timers.target
  - path: /usr/local/bin/bootstrap.sh
    permissions: "0755"
    content: |
      #!/usr/bin/env bash
      set -euo pipefail
      set -a;source /etc/droplet.env;source /etc/habitat-parsed.env 2>/dev/null||true;set +a
      REPO="dfrysinger/hatchery";DIR="/opt/hatchery"
      VER=$(cat /etc/hatchery-version 2>/dev/null||echo "main")
      log(){ echo "[bootstrap] $*";}
      notify(){ [ -x /usr/local/bin/tg-notify.sh ]&&/usr/local/bin/tg-notify.sh "$1" 2>/dev/null||true;}
      fetch(){ local u="$1" d="$2" i;for i in 1 2 3;do curl -fSL --max-time 60 -o "$d" "$u"&&return 0;sleep $((i*5));done;notify "bootstrap: fetch failed -- $u";return 1;}
      mkdir -p "$DIR";T=$(mktemp)
      if [ "$VER" = "main" ];then
        log "Fetching main";fetch "https://github.com/${REPO}/archive/refs/heads/main.tar.gz" "$T"
        tar -xzf "$T" --strip-components=1 -C "$DIR"
      else
        log "Fetching v${VER}";S=$(mktemp);BU="https://github.com/${REPO}/releases/download/v${VER}"
        fetch "${BU}/hatchery-${VER}.tar.gz" "$T"
        if fetch "${BU}/sha256sums.txt" "$S" 2>/dev/null;then
          E=$(grep "hatchery-${VER}.tar.gz" "$S"|awk '{print $1}');A=$(sha256sum "$T"|awk '{print $1}')
          [ "$E" != "$A" ]&&{ notify "bootstrap: SHA256 mismatch";exit 1;}
        fi
        tar -xzf "$T" -C "$DIR";rm -f "$S"
      fi
      rm -f "$T";chmod +x "$DIR"/scripts/*.sh 2>/dev/null||true
      for f in "$DIR"/scripts/*.sh;do bn=$(basename "$f")
        case "$bn" in bootstrap.sh);;phase1-critical.sh|phase2-background.sh|build-full-config.sh)cp "$f" /usr/local/sbin/;;*)cp "$f" /usr/local/bin/;;esac;done
      for f in "$DIR"/scripts/*.py;do [ -f "$f" ]&&cp "$f" /usr/local/bin/&&chmod 755 "/usr/local/bin/$(basename "$f")";done
      [ -f "$DIR/gmail-api.py" ]&&cp "$DIR/gmail-api.py" /usr/local/bin/gmail-api.py&&chmod 755 /usr/local/bin/gmail-api.py
      [ -f "$DIR/set-council-group.sh" ]&&cp "$DIR/set-council-group.sh" /usr/local/bin/set-council-group.telegram.sh&&chmod 755 /usr/local/bin/set-council-group.telegram.sh
      chmod +x /usr/local/sbin/*.sh /usr/local/bin/*.sh 2>/dev/null||true
      notify "bootstrap: hatchery ${VER} installed -- starting phase1"
      /usr/local/sbin/phase1-critical.sh
users:
  - default
runcmd:
  - [bash, -lc, "/usr/local/bin/bootstrap.sh>>/var/log/bootstrap.log 2>&1"]
  - [bash, -lc, "set -a;source /etc/droplet.env;set +a;python3 /usr/local/bin/parse-habitat.py"]
  - [bash, -lc, "systemctl daemon-reload;systemctl enable --now api-server;ufw allow 8080/tcp"]
  - [bash, -lc, "systemctl enable post-boot-check.service"]
  - [bash, -lc, "/usr/local/bin/schedule-destruct.sh"]
  - [bash, -lc, "/usr/local/bin/rename-bots.sh"]
