"""Tests for hc_* isolation-aware service management in lib-health-check.sh.

These test the function dispatch logic (session→systemctl, container→docker)
without actually running docker or systemctl. We verify the correct commands
are generated by capturing them via wrapper functions.
"""
import subprocess
import os
import pytest

SCRIPT_DIR = os.path.join(os.path.dirname(__file__), '..', 'scripts')
LIB_PATH = os.path.join(SCRIPT_DIR, 'lib-health-check.sh')
LIB_ENV_PATH = os.path.join(SCRIPT_DIR, 'lib-env.sh')


def run_hc(code, env=None, check=True):
    """Run bash code with lib-health-check.sh sourced, mocking externals."""
    full_env = {
        'PATH': os.environ.get('PATH', '/usr/bin:/bin'),
        'HOME': '/tmp/test-home',
        'USERNAME': 'bot',
        'HC_USERNAME': 'bot',
        # Prevent env_load from failing
        'TEST_MODE': '1',
    }
    if env:
        full_env.update(env)

    # Source lib-env.sh first (provides d() and env_load), then lib-health-check.sh
    # Mock systemctl/docker/journalctl/curl to capture the command
    script = f"""
set -uo pipefail

# Stub out d() and env_load to prevent failures
d() {{ echo "${{1:-}}"; }}
env_load() {{ return 0; }}
export -f d env_load
type d &>/dev/null || true

source "{LIB_PATH}"

# Mock external commands — just echo what would be called
systemctl() {{ echo "SYSTEMCTL $*"; }}
docker() {{ echo "DOCKER $*"; }}
journalctl() {{ echo "JOURNALCTL $*"; }}
curl() {{ echo "CURL $*"; }}
export -f systemctl docker journalctl curl

{code}
"""
    result = subprocess.run(
        ['bash', '-c', script],
        capture_output=True, text=True, env=full_env
    )
    if check and result.returncode != 0:
        raise AssertionError(
            f"bash exited {result.returncode}\nstdout: {result.stdout}\nstderr: {result.stderr}"
        )
    return result


# =========================================================================
# hc_restart_service
# =========================================================================

class TestHcRestartService:
    def test_session_mode_uses_systemctl(self):
        r = run_hc('hc_restart_service "council"', env={'ISOLATION': 'session'})
        assert 'SYSTEMCTL restart openclaw-council' in r.stdout

    def test_container_mode_uses_docker_compose(self):
        r = run_hc('hc_restart_service "sandbox"', env={'ISOLATION': 'container'})
        assert 'DOCKER compose' in r.stdout
        assert 'restart' in r.stdout
        assert 'openclaw-sandbox' in r.stdout

    def test_default_isolation_is_session(self):
        r = run_hc('hc_restart_service "council"', env={})
        assert 'SYSTEMCTL restart openclaw-council' in r.stdout


# =========================================================================
# hc_is_service_active
# =========================================================================

class TestHcIsServiceActive:
    def test_session_mode_uses_systemctl(self):
        r = run_hc('hc_is_service_active "council"', env={'ISOLATION': 'session'})
        assert 'SYSTEMCTL is-active --quiet openclaw-council' in r.stdout

    def test_container_mode_uses_docker_inspect(self):
        """Verify container mode calls docker inspect and checks for 'healthy'."""
        # Mock docker to return "healthy" — function should succeed (rc=0)
        r = run_hc(
            'docker() { echo "healthy"; }; export -f docker; '
            'hc_is_service_active "sandbox" && echo "SERVICE_ACTIVE" || echo "SERVICE_INACTIVE"',
            env={'ISOLATION': 'container'}
        )
        assert 'SERVICE_ACTIVE' in r.stdout

    def test_container_mode_unhealthy_returns_false(self):
        """When docker inspect returns non-healthy, function returns false."""
        r = run_hc(
            'docker() { echo "unhealthy"; }; export -f docker; '
            'hc_is_service_active "sandbox" && echo "SERVICE_ACTIVE" || echo "SERVICE_INACTIVE"',
            env={'ISOLATION': 'container'}
        )
        assert 'SERVICE_INACTIVE' in r.stdout


# =========================================================================
# hc_service_logs
# =========================================================================

class TestHcServiceLogs:
    def test_session_mode_uses_journalctl(self):
        r = run_hc('hc_service_logs "council"', env={'ISOLATION': 'session'})
        assert 'JOURNALCTL' in r.stdout
        assert 'openclaw-council' in r.stdout

    def test_container_mode_uses_docker_logs(self):
        r = run_hc('hc_service_logs "sandbox" 100', env={'ISOLATION': 'container'})
        assert 'DOCKER compose' in r.stdout
        assert 'logs' in r.stdout
        assert '100' in r.stdout

    def test_default_lines_50(self):
        r = run_hc('hc_service_logs "council"', env={'ISOLATION': 'session'})
        assert '50' in r.stdout


# =========================================================================
# hc_stop_service
# =========================================================================

class TestHcStopService:
    def test_session_mode_uses_systemctl(self):
        r = run_hc('hc_stop_service "council"', env={'ISOLATION': 'session'})
        assert 'SYSTEMCTL stop openclaw-council' in r.stdout

    def test_container_mode_uses_compose_down(self):
        r = run_hc('hc_stop_service "sandbox"', env={'ISOLATION': 'container'})
        assert 'DOCKER compose' in r.stdout
        assert 'down' in r.stdout


# =========================================================================
# hc_curl_gateway
# =========================================================================

class TestHcCurlGateway:
    def test_session_mode_direct_curl(self):
        r = run_hc('hc_curl_gateway "council" "/api/health"', env={
            'ISOLATION': 'session', 'GROUP_PORT': '18790'
        })
        assert 'CURL -sf http://127.0.0.1:18790/api/health' in r.stdout

    def test_container_host_network_direct_curl(self):
        r = run_hc('hc_curl_gateway "sandbox" "/"', env={
            'ISOLATION': 'container', 'NETWORK_MODE': 'host', 'GROUP_PORT': '18791'
        })
        assert 'CURL -sf http://127.0.0.1:18791/' in r.stdout

    def test_container_isolated_network_uses_docker_exec(self):
        r = run_hc('hc_curl_gateway "sandbox" "/api/health"', env={
            'ISOLATION': 'container', 'NETWORK_MODE': 'isolated', 'GROUP_PORT': '18791'
        })
        assert 'DOCKER exec openclaw-sandbox' in r.stdout
        assert '18791' in r.stdout

    def test_default_path_is_root(self):
        r = run_hc('hc_curl_gateway "council"', env={
            'ISOLATION': 'session', 'GROUP_PORT': '18790'
        })
        assert '18790/' in r.stdout


# =========================================================================
# Syntax
# =========================================================================

class TestSyntax:
    def test_bash_n_passes(self):
        r = subprocess.run(['bash', '-n', LIB_PATH], capture_output=True, text=True)
        assert r.returncode == 0, f"bash -n failed: {r.stderr}"
