#!/usr/bin/env python3
"""Tests for XFCE theme configuration.

With slim YAML approach, desktop/theme configuration is in:
- scripts/phase2-background.sh - apt packages and desktop setup
- scripts/build-full-config.sh - xfwm4/xfce config generation

Ensures that when a theme is specified in xfwm4 config, the corresponding
package is included in the apt install list.
"""
import re
import os
import pytest


REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SCRIPTS_DIR = os.path.join(REPO_ROOT, "scripts")


def read_phase2_script():
    """Read phase2-background.sh content."""
    path = os.path.join(SCRIPTS_DIR, "phase2-background.sh")
    with open(path, "r") as f:
        return f.read()


def read_build_config_script():
    """Read build-full-config.sh content."""
    path = os.path.join(SCRIPTS_DIR, "build-full-config.sh")
    with open(path, "r") as f:
        return f.read()


class TestXfceTheme:
    """Test that XFCE theme configuration matches installed packages."""

    def test_yaru_theme_package_installed_when_yaru_theme_specified(self):
        """If xfwm4 config specifies Yaru theme, yaru-theme-gtk must be installed."""
        phase2 = read_phase2_script()
        build_config = read_build_config_script()
        
        # Check if any Yaru theme variant is specified in xfwm4 config
        xfwm4_theme_match = re.search(r'xfwm4.*theme.*type="string"\s+value="(Yaru[^"]*)"', build_config)
        
        if xfwm4_theme_match:
            theme_name = xfwm4_theme_match.group(1)
            # If Yaru theme is used, yaru-theme-gtk must be in package list
            assert "yaru-theme-gtk" in phase2, \
                f"Theme '{theme_name}' requires yaru-theme-gtk package but it's not in apt install list"

    def test_theme_package_in_desktop_environment_section(self):
        """yaru-theme-gtk should be installed with desktop environment packages."""
        content = read_phase2_script()
        
        # Look for the pattern: apt-get install block with xfce4 and yaru-theme-gtk
        de_match = re.search(
            r'desktop-environment.*?apt-get install.*?xfce4.*?yaru-theme-gtk',
            content,
            re.DOTALL
        )
        
        if not de_match:
            # Also try with different marker format
            de_match = re.search(
                r'\$S\s+\d+\s+"desktop-environment".*?apt-get install.*?xfce4.*?yaru-theme-gtk',
                content,
                re.DOTALL
            )
        
        assert de_match, (
            "Could not find desktop-environment apt install block with yaru-theme-gtk.\n"
            "Expected: apt-get install block containing xfce4 and yaru-theme-gtk"
        )

    def test_xfwm4_theme_config_exists(self):
        """Verify xfwm4 theme configuration is present.
        
        With slim YAML approach, the xfwm4 config may be in:
        - A separate config template file
        - Generated by phase2-background.sh
        - In archive/hatch-full.yaml for reference
        
        This test checks for the theme package installation as the key signal.
        """
        phase2 = read_phase2_script()
        
        # The key check is that yaru-theme-gtk is installed
        # The xfwm4.xml config is set up during desktop provisioning
        assert 'yaru-theme-gtk' in phase2 or 'Yaru' in phase2, \
            "Desktop theme setup should reference Yaru theme"

    def test_icon_theme_package_installed(self):
        """Verify icon theme package is installed."""
        content = read_phase2_script()
        
        # elementary-xfce-icon-theme should be installed
        assert "elementary-xfce-icon-theme" in content, \
            "elementary-xfce-icon-theme package should be installed"
