"""
Systemd unit linter — catches known footguns in generated service/path files.

Prevents:
- StartLimitBurst in [Service] (silently ignored, must be in [Unit])
- Restart=always (infinite crash loops, must be on-failure)
- Missing CI=true (causes @clack/prompts stdin block in non-TTY context)
- Missing StartLimitBurst (no crash loop protection)
- ExecStartPost scripts using 'local' outside functions
"""

import os
import re

import pytest

REPO_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SCRIPTS_DIR = os.path.join(REPO_DIR, "scripts")


def read_generator_script(name):
    """Read a generator script and return its content."""
    path = os.path.join(SCRIPTS_DIR, name)
    if not os.path.exists(path):
        return None
    with open(path) as f:
        return f.read()


def parse_unit_sections(unit_text):
    """Parse a systemd unit file into sections."""
    sections = {}
    current_section = None
    for line in unit_text.strip().splitlines():
        line = line.strip()
        if line.startswith("[") and line.endswith("]"):
            current_section = line[1:-1]
            sections[current_section] = {}
        elif "=" in line and current_section:
            key, _, value = line.partition("=")
            key = key.strip()
            # Accumulate multiple values for same key (e.g., Environment)
            if key in sections[current_section]:
                if isinstance(sections[current_section][key], list):
                    sections[current_section][key].append(value.strip())
                else:
                    sections[current_section][key] = [
                        sections[current_section][key], value.strip()
                    ]
            else:
                sections[current_section][key] = value.strip()
    return sections


class TestSessionUnits:
    """Lint session service generator for systemd footguns."""

    @pytest.fixture(autouse=True)
    def setup(self):
        self.content = read_generator_script("generate-session-services.sh")
        if not self.content:
            pytest.skip("generate-session-services.sh not found")

    def test_start_limit_burst_not_in_service_section(self):
        """StartLimitBurst must not appear after [Service] header."""
        in_service = False
        for line in self.content.splitlines():
            if "[Service]" in line:
                in_service = True
            elif line.strip().startswith("[") and line.strip().endswith("]"):
                in_service = False
            if in_service and "StartLimitBurst" in line:
                pytest.fail("StartLimitBurst in [Service] section — must be in [Unit]")

    def test_start_limit_burst_in_unit_section(self):
        """StartLimitBurst must appear after [Unit] header."""
        in_unit = False
        for line in self.content.splitlines():
            if "[Unit]" in line:
                in_unit = True
            elif line.strip().startswith("[") and line.strip().endswith("]"):
                in_unit = False
            if in_unit and "StartLimitBurst" in line:
                return  # Found it in [Unit] — pass
        pytest.fail("StartLimitBurst not found in [Unit] section")

    def test_restart_on_failure(self):
        """Restart must be on-failure, never always."""
        assert "Restart=on-failure" in self.content
        assert "Restart=always" not in self.content

    def test_ci_env_set(self):
        """CI=true prevents @clack/prompts stdin block."""
        assert "CI=true" in self.content


class TestContainerUnits:
    """Lint container service generator for systemd footguns."""

    @pytest.fixture(autouse=True)
    def setup(self):
        # Container units are generated by generate-docker-compose.sh
        self.content = read_generator_script("generate-docker-compose.sh")
        if not self.content:
            pytest.skip("generate-docker-compose.sh not found")

    def test_start_limit_burst_not_in_service_section(self):
        """StartLimitBurst must not appear after [Service] in container unit heredoc."""
        in_service = False
        for line in self.content.splitlines():
            if "[Service]" in line:
                in_service = True
            elif line.strip().startswith("[") and line.strip().endswith("]"):
                in_service = False
            if in_service and "StartLimitBurst" in line:
                pytest.fail("StartLimitBurst in [Service] section — must be in [Unit]")

    def test_restart_on_failure(self):
        """Restart must be on-failure, never always."""
        assert "Restart=always" not in self.content


class TestSafeguardPathUnits:
    """Validate .path units clean up watched files."""

    def test_safe_mode_handler_removes_unhealthy_marker(self):
        """safe-mode-handler.sh must remove the unhealthy marker on ALL exit paths."""
        handler = os.path.join(SCRIPTS_DIR, "safe-mode-handler.sh")
        if not os.path.exists(handler):
            pytest.skip("safe-mode-handler.sh not found")

        with open(handler) as f:
            content = f.read()

        # Must have a trap that runs cleanup
        assert re.search(r'trap\b.*cleanup|trap\b.*EXIT', content), \
            "safe-mode-handler.sh missing EXIT trap for cleanup"

        # Must remove unhealthy marker
        assert "rm -f" in content and "HC_UNHEALTHY_MARKER" in content, \
            "safe-mode-handler.sh must remove HC_UNHEALTHY_MARKER to prevent .path re-trigger"

    def test_handler_stops_service_on_terminal_failure(self):
        """Terminal failure paths must stop the service."""
        handler = os.path.join(SCRIPTS_DIR, "safe-mode-handler.sh")
        if not os.path.exists(handler):
            pytest.skip("safe-mode-handler.sh not found")

        with open(handler) as f:
            content = f.read()

        # Must call hc_stop_service on exhausted-attempts path
        assert content.count("hc_stop_service") >= 2, \
            "safe-mode-handler.sh must call hc_stop_service on ALL terminal failure paths"


class TestHealthCheckScripts:
    """Validate health check scripts don't have bash footguns."""

    def test_no_local_outside_functions(self):
        """'local' keyword must only appear inside functions."""
        for script_name in ["gateway-health-check.sh", "gateway-e2e-check.sh"]:
            script_path = os.path.join(SCRIPTS_DIR, script_name)
            if not os.path.exists(script_path):
                continue

            with open(script_path) as f:
                lines = f.readlines()

            in_function = False
            brace_depth = 0
            for i, line in enumerate(lines, 1):
                stripped = line.strip()

                # Track function boundaries (simplified)
                if re.match(r'^[a-zA-Z_]\w*\s*\(\)', stripped):
                    in_function = True
                    brace_depth = 0
                if in_function:
                    brace_depth += stripped.count("{") - stripped.count("}")
                    if brace_depth <= 0 and in_function and "{" not in stripped:
                        in_function = False

                if stripped.startswith("local ") and not in_function:
                    pytest.fail(
                        f"{script_name}:{i}: 'local' outside function — "
                        f"fatal error under set -euo pipefail"
                    )


class TestDockerCompose:
    """Validate docker-compose security settings."""

    def test_compose_restart_has_retry_cap(self):
        """Docker restart policy must have a retry cap."""
        generator = os.path.join(SCRIPTS_DIR, "generate-docker-compose.sh")
        if not os.path.exists(generator):
            pytest.skip("generate-docker-compose.sh not found")

        with open(generator) as f:
            content = f.read()

        # Should use on-failure with a cap, not unlimited
        assert "on-failure:" in content or "on_failure" in content, \
            "Docker restart policy must specify retry cap (on-failure:N)"

    def test_compose_cap_drop_all(self):
        """Containers must drop all capabilities."""
        generator = os.path.join(SCRIPTS_DIR, "generate-docker-compose.sh")
        if not os.path.exists(generator):
            pytest.skip("generate-docker-compose.sh not found")

        with open(generator) as f:
            content = f.read()

        assert "ALL" in content, "Containers must cap_drop: ALL"

    def test_compose_no_new_privileges(self):
        """Containers must set no-new-privileges."""
        generator = os.path.join(SCRIPTS_DIR, "generate-docker-compose.sh")
        if not os.path.exists(generator):
            pytest.skip("generate-docker-compose.sh not found")

        with open(generator) as f:
            content = f.read()

        assert "no-new-privileges" in content, \
            "Containers must set security_opt: no-new-privileges"
