#!/bin/bash
# =============================================================================
# generate-docker-compose.sh — Generate per-group docker-compose.yaml files
# =============================================================================
# THIN GENERATOR: Creates docker-compose.yaml + systemd unit per container group.
#
# All shared concerns (directories, config, credentials, tokens, env files,
# safeguard/E2E units, manifest) are handled by the orchestrator
# (build-full-config.sh) using lib-isolation.sh BEFORE this script runs.
#
# Inputs:
#   MANIFEST           — path to /etc/openclaw-groups.json (runtime SSOT)
#   ISOLATION_GROUPS   — comma-separated list of container groups to generate
#   ISOLATION_DEFAULT  — must be "container" for this generator
#   USERNAME / SVC_USER — system user
#   HOME_DIR           — home directory
#   HABITAT_NAME       — habitat name (for unit descriptions)
#   CONTAINER_IMAGE    — Docker image (default: hatchery/agent:latest)
#
# Outputs:
#   ~/.openclaw/compose/{group}/docker-compose.yaml — one per group
#   ${COMPOSE_SYSTEMD_DIR}/openclaw-container-{group}.service — systemd units
#
# Env:
#   COMPOSE_SYSTEMD_DIR — systemd output dir (default: /etc/systemd/system)
#   DRY_RUN             — if set, write files only (no docker/systemctl)
#   START_SERVICES      — if "true", also start services after enabling
# =============================================================================
set -euo pipefail
umask 022

# --- Source lib-isolation for manifest reading ---
for _lib_path in /usr/local/sbin /usr/local/bin "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"; do
  [ -f "$_lib_path/lib-isolation.sh" ] && { source "$_lib_path/lib-isolation.sh"; break; }
done
type get_group_port &>/dev/null || { echo "FATAL: lib-isolation.sh not found" >&2; exit 1; }

# --- Configuration ---
ISOLATION="${ISOLATION_DEFAULT:-none}"
ISO_GROUPS="${ISOLATION_GROUPS:-}"
SVC_USER="${SVC_USER:-${USERNAME:-bot}}"
HOME_DIR="${HOME_DIR:-/home/${SVC_USER}}"
HABITAT="${HABITAT_NAME:-default}"
BASE_IMAGE="${CONTAINER_IMAGE:-hatchery/agent:latest}"
SYSTEMD_DIR="${COMPOSE_SYSTEMD_DIR:-${UNIT_OUTPUT_DIR:-/etc/systemd/system}}"

# --- Skip if not container mode or no groups ---
if [ "$ISOLATION" != "container" ]; then
    echo "Isolation mode is '$ISOLATION' — no docker-compose needed."
    exit 0
fi

if [ -z "$ISO_GROUPS" ]; then
    echo "No isolation groups defined — no docker-compose needed."
    exit 0
fi

IFS=',' read -ra CONTAINER_GROUPS <<< "$ISO_GROUPS"

if [ ${#CONTAINER_GROUPS[@]} -eq 0 ]; then
    echo "No container groups — nothing to do."
    exit 0
fi

echo "Generating docker-compose files for ${#CONTAINER_GROUPS[@]} group(s)..."

# --- Generate per-group compose file + systemd unit ---
for group in "${CONTAINER_GROUPS[@]}"; do
    # Read all metadata from manifest (generated by orchestrator)
    port=$(jq -r --arg g "$group" '.groups[$g].port' "$MANIFEST" 2>/dev/null)
    config_path=$(jq -r --arg g "$group" '.groups[$g].configPath // empty' "$MANIFEST" 2>/dev/null)
    state_path=$(jq -r --arg g "$group" '.groups[$g].statePath // empty' "$MANIFEST" 2>/dev/null)
    env_file=$(jq -r --arg g "$group" '.groups[$g].envFile // empty' "$MANIFEST" 2>/dev/null)
    compose_path=$(jq -r --arg g "$group" '.groups[$g].composePath // empty' "$MANIFEST" 2>/dev/null)
    network=$(jq -r --arg g "$group" '.groups[$g].network // "host"' "$MANIFEST" 2>/dev/null)
    agents_json=$(jq -r --arg g "$group" '.groups[$g].agents // [] | join(",")' "$MANIFEST" 2>/dev/null)
    # Resource limits from agent env vars (pipe-delimited: "mem|cpu")
    IFS='|' read -r mem_limit cpu_limit <<< "$(get_group_resources "$group")"

    [ -z "$port" ] || [ "$port" = "null" ] && { echo "ERROR: No port for group '${group}'" >&2; exit 1; }
    [ -z "$config_path" ] && { echo "ERROR: No configPath for group '${group}'" >&2; exit 1; }
    [ -z "$compose_path" ] && { echo "ERROR: No composePath for group '${group}'" >&2; exit 1; }

    config_dir="$(dirname "$config_path")"
    compose_dir="$(dirname "$compose_path")"
    mkdir -p "$compose_dir"

    # --- Build volumes list ---
    # Option A: minimal mounts, no host scripts
    volumes=""
    # OpenClaw config (read-only — generated by orchestrator)
    volumes="${volumes}      - ${config_path}:${HOME_DIR}/.openclaw/openclaw.json:ro"$'\n'
    # Gateway token (read-only)
    volumes="${volumes}      - ${config_dir}/gateway-token.txt:${HOME_DIR}/.openclaw/gateway-token.txt:ro"$'\n'
    # Session state dir (rw — contains auth-profiles symlinks, transcripts)
    volumes="${volumes}      - ${state_path}:${HOME_DIR}/.openclaw-sessions/${group}:rw"$'\n'
    # Per-agent workspaces (rw — agents write memory, etc.)
    IFS=',' read -ra agent_ids <<< "$agents_json"
    for agent_id in "${agent_ids[@]}"; do
        [ -z "$agent_id" ] && continue
        volumes="${volumes}      - ${HOME_DIR}/clawd/agents/${agent_id}:${HOME_DIR}/clawd/agents/${agent_id}:rw"$'\n'
    done
    # Shared workspace (rw — cross-agent collaboration)
    volumes="${volumes}      - ${HOME_DIR}/clawd/shared:${HOME_DIR}/clawd/shared:rw"
    # Additional shared paths from habitat config
    if [ -n "${ISOLATION_SHARED_PATHS:-}" ]; then
        IFS=',' read -ra shared_paths <<< "$ISOLATION_SHARED_PATHS"
        for sp in "${shared_paths[@]}"; do
            [ -z "$sp" ] && continue
            volumes="${volumes}"$'\n'"      - ${sp}:${sp}:rw"
        done
    fi

    # --- Build network section ---
    network_section=""
    networks_block=""
    if [ "$network" = "host" ]; then
        network_section="    network_mode: host"
    else
        # Isolated network — internal bridge (no external access)
        # Port mapping required so host health checks can reach the gateway
        network_section="    networks:
      - internal
    ports:
      - \"${port}:${port}\"
    dns: []"
        networks_block="
networks:
  internal:
    driver: bridge
    internal: true"
    fi

    # --- Build resource limits ---
    resource_lines=""
    if [ -n "$mem_limit" ]; then
        resource_lines="${resource_lines}    mem_limit: ${mem_limit}"$'\n'
        resource_lines="${resource_lines}    memswap_limit: ${mem_limit}"$'\n'  # Prevent swap
    fi
    if [ -n "$cpu_limit" ]; then
        resource_lines="${resource_lines}    cpus: ${cpu_limit}"$'\n'
    fi

    # --- Security hardening ---
    security_section="    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp:size=256M
      - /run:size=64M
      - ${HOME_DIR}/.npm:size=64M
      - ${HOME_DIR}/.cache:size=64M
    pids_limit: 256"

    # Resolve UID/GID for user: directive (host user must match container user)
    bot_uid=$(id -u "$SVC_USER" 2>/dev/null || echo 1000)
    bot_gid=$(id -g "$SVC_USER" 2>/dev/null || echo 1000)

    # --- Write docker-compose.yaml ---
    cat > "$compose_path" <<COMPOSE
services:
  openclaw-${group}:
    image: ${BASE_IMAGE}
    container_name: openclaw-${group}
    user: "${bot_uid}:${bot_gid}"
    restart: on-failure
${network_section}
    command: ["--bind", "loopback", "--port", "${port}"]
    env_file:
      - ${env_file}
    environment:
      - NODE_ENV=production
      - NODE_OPTIONS=--experimental-sqlite
      # Override host paths from group.env to match container mount points
      - OPENCLAW_CONFIG_PATH=/home/${SVC_USER}/.openclaw/openclaw.json
      - OPENCLAW_STATE_DIR=/home/${SVC_USER}/.openclaw-sessions/${group}
    volumes:
${volumes}
${resource_lines}${security_section}
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://127.0.0.1:${port}/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 60s
${networks_block}
COMPOSE

    echo "  [${group}] port=${port} network=${network} → ${compose_path}"

    # --- Generate container systemd unit ---
    cat > "${SYSTEMD_DIR}/openclaw-container-${group}.service" <<SVCFILE
[Unit]
Description=OpenClaw Container - ${group} (${HABITAT})
After=network.target docker.service
Requires=docker.service

[Service]
Type=oneshot
RemainAfterExit=yes
User=root
WorkingDirectory=${HOME_DIR}

EnvironmentFile=${env_file}
ExecStart=/usr/bin/docker compose -f ${compose_path} -p openclaw-${group} up -d --wait
ExecStop=/usr/bin/docker compose -f ${compose_path} -p openclaw-${group} down
ExecStartPost=+/bin/bash -c 'source ${env_file} && RUN_MODE=execstartpost /usr/local/bin/gateway-health-check.sh'

Restart=on-failure
RestartSec=10
RestartPreventExitStatus=2
TimeoutStartSec=180
TimeoutStopSec=60

[Install]
WantedBy=multi-user.target
SVCFILE

    echo "  [${group}] → openclaw-container-${group}.service"
done

# --- Install and enable services ---
if [ -z "${DRY_RUN:-}" ]; then
    echo "Installing container services..."
    systemctl daemon-reload

    for group in "${CONTAINER_GROUPS[@]}"; do
        systemctl enable "openclaw-container-${group}.service"
        if [ "${START_SERVICES:-false}" = "true" ]; then
            systemctl start "openclaw-container-${group}.service" || {
                echo "  [${group}] Service start returned non-zero"
            }
        else
            echo "  [${group}] Service enabled (caller will start)"
        fi
    done

    echo "Container services enabled${START_SERVICES:+ and started}."
else
    echo "DRY_RUN mode — compose files and units written"
fi

echo "Generated ${#CONTAINER_GROUPS[@]} container compose file(s) for habitat '${HABITAT}'"
