#!/bin/bash
# =============================================================================
# generate-session-services.sh — Generate per-group systemd service units
# =============================================================================
# THIN GENERATOR: Only creates the systemd .service file per session group.
#
# All shared concerns (directories, config, credentials, tokens, env files,
# safeguard/E2E units, manifest) are handled by the orchestrator
# (build-full-config.sh) using lib-isolation.sh BEFORE this script runs.
#
# Inputs:
#   MANIFEST         — path to /etc/openclaw-groups.json (runtime SSOT)
#   ISOLATION_GROUPS — comma-separated list of session groups to generate
#   ISOLATION_DEFAULT — must be "session" for this generator
#   USERNAME / SVC_USER — system user running the gateway
#   HOME_DIR         — home directory
#   HABITAT_NAME     — habitat name (for unit descriptions)
#
# Outputs:
#   ${OUTPUT_DIR}/openclaw-{group}.service — one systemd unit per group
#
# Env:
#   SESSION_OUTPUT_DIR — output directory (default: /etc/systemd/system)
#   DRY_RUN            — if set, write units only (no systemctl)
#   START_SERVICES     — if "true", also start services after enabling
# =============================================================================
set -euo pipefail
umask 022

# --- Source lib-isolation for manifest reading ---
for _lib_path in /usr/local/sbin /usr/local/bin "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"; do
  [ -f "$_lib_path/lib-isolation.sh" ] && { source "$_lib_path/lib-isolation.sh"; break; }
done
type get_group_port &>/dev/null || { echo "FATAL: lib-isolation.sh not found" >&2; exit 1; }

# --- Configuration ---
ISOLATION="${ISOLATION_DEFAULT:-none}"
ISO_GROUPS="${ISOLATION_GROUPS:-}"
SVC_USER="${SVC_USER:-${USERNAME:-bot}}"
HOME_DIR="${HOME_DIR:-/home/${SVC_USER}}"
HABITAT="${HABITAT_NAME:-default}"
OUTPUT_DIR="${SESSION_OUTPUT_DIR:-/etc/systemd/system}"

# --- Skip if no groups ---
# NOTE: Do NOT gate on ISOLATION_DEFAULT here. In mixed-mode habitats,
# ISOLATION_DEFAULT may be "container" but some groups use "session".
# The caller (build-full-config.sh) pre-filters and only passes session
# groups via ISOLATION_GROUPS. Trust the caller.

if [ -z "$ISO_GROUPS" ]; then
    echo "No isolation groups defined — no session services needed."
    exit 0
fi

IFS=',' read -ra SESSION_GROUPS <<< "$ISO_GROUPS"

if [ ${#SESSION_GROUPS[@]} -eq 0 ]; then
    echo "No session groups — nothing to do."
    exit 0
fi

echo "Generating session services for ${#SESSION_GROUPS[@]} group(s)..."

# --- Generate systemd .service per group ---
for group in "${SESSION_GROUPS[@]}"; do
    # Read port from manifest (generated by orchestrator)
    port=$(get_group_port "$group")
    if [ -z "$port" ]; then
        echo "ERROR: No port found for group '${group}' in manifest" >&2
        exit 1
    fi

    # Read paths from manifest
    config_path=$(jq -r --arg g "$group" '.groups[$g].configPath // empty' "$MANIFEST" 2>/dev/null)
    state_path=$(jq -r --arg g "$group" '.groups[$g].statePath // empty' "$MANIFEST" 2>/dev/null)
    env_file=$(jq -r --arg g "$group" '.groups[$g].envFile // empty' "$MANIFEST" 2>/dev/null)

    [ -z "$config_path" ] && { echo "ERROR: No configPath for group '${group}'" >&2; exit 1; }
    [ -z "$state_path" ] && { echo "ERROR: No statePath for group '${group}'" >&2; exit 1; }
    [ -z "$env_file" ] && { echo "ERROR: No envFile for group '${group}'" >&2; exit 1; }

    # Generate the systemd service unit — this is the ONLY output of this script
    cat > "${OUTPUT_DIR}/openclaw-${group}.service" <<SVCFILE
[Unit]
Description=OpenClaw Session - ${group} (${HABITAT})
After=network.target desktop.service
Wants=desktop.service

[Service]
Type=simple
User=${SVC_USER}
WorkingDirectory=${HOME_DIR}
ExecStart=/usr/local/bin/openclaw gateway --bind loopback --port ${port}
ExecStartPost=+/bin/bash -c 'source ${env_file} && RUN_MODE=execstartpost /usr/local/bin/gateway-health-check.sh'
Restart=on-failure
RestartSec=10
StartLimitBurst=5
StartLimitIntervalSec=300
RestartPreventExitStatus=2
TimeoutStartSec=180
EnvironmentFile=${env_file}
Environment=CI=true
Environment=NODE_ENV=production
Environment=PATH=/usr/local/bin:/usr/bin
Environment=DISPLAY=:10
Environment=OPENCLAW_CONFIG_PATH=${config_path}
Environment=OPENCLAW_STATE_DIR=${state_path}

[Install]
WantedBy=multi-user.target
SVCFILE

    echo "  [${group}] port=${port} → openclaw-${group}.service"
done

# --- Install and enable services ---
if [ -z "${DRY_RUN:-}" ]; then
    echo "Installing systemd services..."
    if [ "$OUTPUT_DIR" != "/etc/systemd/system" ]; then
        for group in "${SESSION_GROUPS[@]}"; do
            cp "${OUTPUT_DIR}/openclaw-${group}.service" /etc/systemd/system/
        done
    fi
    systemctl daemon-reload

    # Stop main openclaw service — session isolation replaces it
    echo "Stopping main openclaw service (replaced by session services)..."
    systemctl stop openclaw 2>/dev/null || true
    systemctl disable openclaw 2>/dev/null || true

    for group in "${SESSION_GROUPS[@]}"; do
        systemctl enable "openclaw-${group}.service"
        if [ "${START_SERVICES:-false}" = "true" ]; then
            systemctl start "openclaw-${group}.service" || {
                echo "  [${group}] Service start returned non-zero (health check may have triggered safe mode)"
            }
        else
            echo "  [${group}] Service enabled (caller will start)"
        fi
    done

    echo "Session services enabled${START_SERVICES:+ and started}."
else
    echo "DRY_RUN mode — services written to ${OUTPUT_DIR}"
fi

echo "Generated ${#SESSION_GROUPS[@]} session service(s) for habitat '${HABITAT}'"
